using System;
using System.Linq;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using DeskGuardBackend.Reports.Models;

namespace DeskGuardBackend.Reports.PDF
{
    public class AmcHealthSummaryReportDocument : IDocument
    {
        private readonly AmcHealthSummaryReportData _data;

        public AmcHealthSummaryReportDocument(AmcHealthSummaryReportData data)
        {
            _data = data;
        }

        public DocumentMetadata GetMetadata()
        {
            return new DocumentMetadata
            {
                Title = "AMC Health Summary Report",
                Author = "DeskGuard Enterprise",
                Subject = $"AMC Health Summary for {_data.CompanyName}"
            };
        }

        public DocumentSettings GetSettings() => DocumentSettings.Default;

        public void Compose(IDocumentContainer container)
        {
            container
                .Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30f, Unit.Point);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontFamily("Segoe UI").FontSize(9f).FontColor("#1F2937"));

                    page.Header().Element(ComposeHeader);
                    page.Content().Element(ComposeContent);
                    page.Footer().Element(ComposeFooter);
                });
        }

        private void ComposeHeader(IContainer container)
        {
            container.PaddingBottom(15f).Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(t => t.Span("DeskGuard").FontSize(18f).Bold().FontColor("#1E3A8A"));
                    col.Item().Text(t => t.Span("AMC Health Summary Report").FontSize(14f).Bold().FontColor("#3B82F6"));
                    col.Item().Text(t => t.Span($"Customer: {_data.CompanyName}").FontSize(10f).SemiBold());
                });

                row.ConstantItem(180f).AlignRight().Column(col =>
                {
                    col.Item().Text(t => t.Span($"Report ID: #{_data.ReportId}").FontSize(8f).FontColor("#6B7280"));
                    col.Item().Text(t => t.Span($"Generated At: {_data.GeneratedAt:yyyy-MM-dd HH:mm:ss}").FontSize(8f).FontColor("#6B7280"));
                    col.Item().Text(t => t.Span($"Generated By: {_data.GeneratedBy}").FontSize(8f).FontColor("#6B7280"));
                });
            });
        }

        private void ComposeContent(IContainer container)
        {
            container.Column(col =>
            {
                // Line separator
                col.Item().LineHorizontal(1f).LineColor("#E5E7EB");
                col.Item().PaddingBottom(10f);

                // Section 1: AMC Info
                col.Item().Element(ComposeReportInformation);
                col.Item().PaddingBottom(15f);

                // Section 2: Executive Summary Cards
                col.Item().Text(t => t.Span("Executive Summary").FontSize(11f).Bold().FontColor("#1E3A8A"));
                col.Item().PaddingBottom(5f);
                col.Item().Element(ComposeExecutiveSummary);
                col.Item().PaddingBottom(15f);

                // Section 3: Recommendations
                col.Item().Text(t => t.Span("Health Recommendations").FontSize(11f).Bold().FontColor("#1E3A8A"));
                col.Item().PaddingBottom(5f);
                col.Item().Element(ComposeRecommendations);
                col.Item().PaddingBottom(15f);

                // Section 4: System Health Table
                col.Item().Text(t => t.Span("System Health Overview").FontSize(11f).Bold().FontColor("#1E3A8A"));
                col.Item().PaddingBottom(5f);
                col.Item().Element(ComposeSystemHealthTable);
                col.Item().PaddingBottom(15f);

                // Section 5: Alert Summary
                col.Item().Text(t => t.Span("Alert Summary").FontSize(11f).Bold().FontColor("#1E3A8A"));
                col.Item().PaddingBottom(5f);
                col.Item().Element(ComposeAlertSummary);
                col.Item().PaddingBottom(15f);

                // Section 6: Change Summary
                col.Item().Text(t => t.Span("Change History Summary").FontSize(11f).Bold().FontColor("#1E3A8A"));
                col.Item().PaddingBottom(5f);
                col.Item().Element(ComposeChangeSummary);
                col.Item().PaddingBottom(15f);

                // Section 7: Security Overview & System Status
                col.Item().Row(row =>
                {
                    row.RelativeItem().Column(secCol =>
                    {
                        secCol.Item().Text(t => t.Span("Security Overview").FontSize(11f).Bold().FontColor("#1E3A8A"));
                        secCol.Item().PaddingBottom(5f);
                        secCol.Item().Element(ComposeSecurityOverview);
                    });
                    
                    row.ConstantItem(15f);

                    row.RelativeItem().Column(statCol =>
                    {
                        statCol.Item().Text(t => t.Span("System Status Summary").FontSize(11f).Bold().FontColor("#1E3A8A"));
                        statCol.Item().PaddingBottom(5f);
                        statCol.Item().Element(ComposeSystemStatusSummary);
                    });
                });
            });
        }

        private void ComposeReportInformation(IContainer container)
        {
            container.Background("#F3F4F6").Padding(10f).Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(t => { t.Span("Customer Name: ").Bold(); t.Span(_data.CompanyName); });
                    col.Item().Text(t => { t.Span("AMC Plan: ").Bold(); t.Span(_data.AmcPlan); });
                    col.Item().Text(t => { t.Span("AMC Start Date: ").Bold(); t.Span(_data.AmcStartDateStr); });
                });

                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(t => { t.Span("AMC End Date: ").Bold(); t.Span(_data.AmcEndDateStr); });
                    col.Item().Text(t => { t.Span("Report Period: ").Bold(); t.Span(_data.ReportPeriodStr); });
                    col.Item().Text(t => { t.Span("Systems Covered: ").Bold(); t.Span(_data.TotalSystems.ToString()); });
                });
            });
        }

        private void ComposeExecutiveSummary(IContainer container)
        {
            container.Column(col =>
            {
                col.Item().Row(row =>
                {
                    StyleCard(row.RelativeItem(), "Total Systems", _data.TotalSystems.ToString(), "💻", "#3B82F6");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Healthy Systems", _data.HealthySystems.ToString(), "🟢", "#10B981");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Warning Systems", _data.WarningSystems.ToString(), "🟡", "#F59E0B");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Critical Systems", _data.CriticalSystems.ToString(), "🔴", "#EF4444");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Offline Systems", _data.OfflineSystems.ToString(), "⚫", "#6B7280");
                });

                col.Item().PaddingTop(6f).Row(row =>
                {
                    StyleCard(row.RelativeItem(), "Avg. Health Score", $"{_data.AverageHealthScore:F1}%", "🛡️", "#1E3A8A");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Open Alerts", _data.OpenAlerts.ToString(), "⚠️", "#EF4444");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Resolved Alerts", _data.ResolvedAlerts.ToString(), "✅", "#10B981");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Hardware Changes", _data.HardwareChangesCount.ToString(), "⚙️", "#8B5CF6");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Software Changes", _data.SoftwareChangesCount.ToString(), "💿", "#EC4899");
                });
            });
        }

        private void StyleCard(IContainer container, string title, string value, string icon, string colorHex)
        {
            container
                .Border(1f)
                .BorderColor("#E5E7EB")
                .Background("#FAFAFA")
                .Padding(8f)
                .Column(col =>
                {
                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Text(t => t.Span(title).FontSize(7.5f).SemiBold().FontColor("#4B5563"));
                        row.ConstantItem(15f).AlignRight().Text(t => t.Span(icon).FontSize(9f));
                    });
                    col.Item().PaddingTop(4f).Text(t => t.Span(value).FontSize(13f).Bold().FontColor(colorHex));
                });
        }

        private void ComposeRecommendations(IContainer container)
        {
            if (_data.HealthRecommendations == null || !_data.HealthRecommendations.Any())
            {
                container.Border(1f).BorderColor("#E5E7EB").Padding(8f).Text(t => t.Span("No Recommendations Available (All systems are healthy and compliant)").Italic().FontColor("#4B5563"));
                return;
            }

            container
                .Border(1f)
                .BorderColor("#EF4444")
                .Background("#FEF2F2")
                .Padding(10f)
                .Column(col =>
                {
                    foreach (var recommendation in _data.HealthRecommendations)
                    {
                        col.Item().Row(row =>
                        {
                            row.ConstantItem(12f).Text(t => t.Span("⚡").FontColor("#EF4444").Bold());
                            row.RelativeItem().Text(t => t.Span(recommendation).FontSize(8.5f).SemiBold());
                        });
                    }
                });
        }

        private void ComposeSystemHealthTable(IContainer container)
        {
            if (_data.Systems == null || !_data.Systems.Any())
            {
                container.Text(t => t.Span("No Data Available").Italic().FontColor("#6B7280"));
                return;
            }

            container.Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(2f); // Name
                    columns.RelativeColumn(2f); // Machine ID
                    columns.RelativeColumn(1.2f); // Health Score
                    columns.RelativeColumn(1.2f); // Current Status
                    columns.RelativeColumn(1.5f); // Last Heartbeat
                    columns.RelativeColumn(1.2f); // CPU Status
                    columns.RelativeColumn(1.2f); // RAM Status
                    columns.RelativeColumn(1.2f); // Disk Status
                    columns.RelativeColumn(1.2f); // Security Status
                    columns.RelativeColumn(1.5f); // Overall Condition
                });

                table.Header(header =>
                {
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Machine Name"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Machine ID"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Health Score"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Status"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Last Heartbeat"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("CPU"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("RAM"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Disk"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Security"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Condition"));
                });

                int index = 0;
                foreach (var system in _data.Systems)
                {
                    var isEven = index % 2 == 0;
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(system.MachineName).FontSize(7.5f).SemiBold());
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(system.MachineId).FontSize(7f).FontColor("#4B5563"));
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span($"{system.HealthScore:F0}%").FontSize(7.5f).Bold().FontColor(GetHealthScoreColor(system.HealthScore)));
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(system.CurrentStatus).FontSize(7.5f).SemiBold().FontColor(GetStatusColor(system.CurrentStatus)));
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(system.LastHeartbeat).FontSize(7f).FontColor("#4B5563"));
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(system.CpuStatus).FontSize(7.5f));
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(system.RamStatus).FontSize(7.5f));
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(system.DiskStatus).FontSize(7.5f));
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(system.SecurityStatus).FontSize(7.5f));
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(system.OverallCondition).FontSize(7.5f).SemiBold());
                    index++;
                }
            });
        }

        private IContainer StyleTableHeader(IContainer container)
        {
            return container
                .Background("#1E3A8A")
                .Padding(4f)
                .AlignMiddle()
                .DefaultTextStyle(x => x.FontColor(Colors.White).FontSize(7.5f).Bold());
        }

        private IContainer StyleTableCell(IContainer container, bool isEven)
        {
            return container
                .Background(isEven ? "#FFFFFF" : "#F9FAFB")
                .BorderBottom(1f)
                .BorderColor("#F3F4F6")
                .Padding(4f)
                .AlignMiddle();
        }

        private string GetHealthScoreColor(double score)
        {
            if (score >= 90) return "#10B981"; // Green
            if (score >= 70) return "#3B82F6"; // Blue
            if (score >= 50) return "#F59E0B"; // Yellow
            return "#EF4444"; // Red
        }

        private string GetStatusColor(string status)
        {
            if (status.Equals("Online", StringComparison.OrdinalIgnoreCase)) return "#10B981";
            if (status.Equals("Offline", StringComparison.OrdinalIgnoreCase)) return "#6B7280";
            if (status.Equals("Warning", StringComparison.OrdinalIgnoreCase)) return "#F59E0B";
            return "#EF4444";
        }

        private void ComposeAlertSummary(IContainer container)
        {
            container.Border(1f).BorderColor("#E5E7EB").Padding(8f).Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(t => { t.Span("Pending Alerts: ").Bold(); t.Span(_data.AlertPendingCount.ToString()); });
                    col.Item().Text(t => { t.Span("Resolved Alerts: ").Bold(); t.Span(_data.AlertResolvedCount.ToString()); });
                    col.Item().Text(t => { t.Span("Critical: ").Bold(); t.Span(_data.AlertCriticalCount.ToString()).FontColor("#EF4444"); });
                    col.Item().Text(t => { t.Span("Important: ").Bold(); t.Span(_data.AlertImportantCount.ToString()).FontColor("#F59E0B"); });
                });

                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(t => { t.Span("Warning: ").Bold(); t.Span(_data.AlertWarningCount.ToString()); });
                    col.Item().Text(t => { t.Span("Information: ").Bold(); t.Span(_data.AlertInfoCount.ToString()); });
                    col.Item().Text(t => { t.Span("Avg Response Time: ").Bold(); t.Span(_data.AverageResponseTime); });
                });

                row.RelativeItem(1.5f).Column(col =>
                {
                    col.Item().Text(t => t.Span("Recent Critical Alerts").FontSize(8f).Bold().FontColor("#1E3A8A"));
                    if (_data.RecentCriticalAlerts == null || !_data.RecentCriticalAlerts.Any())
                    {
                        col.Item().Text(t => t.Span("No Critical Alerts Detected").Italic().FontSize(7f).FontColor("#6B7280"));
                    }
                    else
                    {
                        foreach (var alert in _data.RecentCriticalAlerts.Take(3))
                        {
                            col.Item().Text(t => t.Span($"• {alert.MachineName}: {alert.Title} ({alert.CreatedAt})").FontSize(7f).FontColor("#EF4444"));
                        }
                    }
                });
            });
        }

        private void ComposeChangeSummary(IContainer container)
        {
            container.Border(1f).BorderColor("#E5E7EB").Padding(8f).Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(t => { t.Span("Hardware Changes: ").Bold(); t.Span(_data.ChangesHardwareCount.ToString()); });
                    col.Item().Text(t => { t.Span("Software Changes: ").Bold(); t.Span(_data.ChangesSoftwareCount.ToString()); });
                    col.Item().Text(t => { t.Span("USB Device Changes: ").Bold(); t.Span(_data.ChangesUsbCount.ToString()); });
                });

                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(t => { t.Span("Configuration Changes: ").Bold(); t.Span(_data.ChangesConfigCount.ToString()); });
                    col.Item().Text(t => { t.Span("Security Changes: ").Bold(); t.Span(_data.ChangesSecurityCount.ToString()); });
                    col.Item().Text(t => { t.Span("Network Changes: ").Bold(); t.Span(_data.ChangesNetworkCount.ToString()); });
                });

                row.RelativeItem(1.5f).Column(col =>
                {
                    col.Item().Text(t => t.Span("Recent Change Log").FontSize(8f).Bold().FontColor("#1E3A8A"));
                    if (_data.RecentChanges == null || !_data.RecentChanges.Any())
                    {
                        col.Item().Text(t => t.Span("No Changes Logged").Italic().FontSize(7f).FontColor("#6B7280"));
                    }
                    else
                    {
                        foreach (var chg in _data.RecentChanges.Take(3))
                        {
                            col.Item().Text(t => t.Span($"• {chg.MachineName}: [{chg.Category}] {chg.ChangeType} ({chg.DetectedAt})").FontSize(7f));
                        }
                    }
                });
            });
        }

        private void ComposeSecurityOverview(IContainer container)
        {
            container.Border(1f).BorderColor("#E5E7EB").Padding(8f).Column(col =>
            {
                col.Item().Text(t => { t.Span("Firewall Enabled: ").Bold(); t.Span($"{_data.FirewallEnabledCount}/{_data.TotalSystems} Systems"); });
                col.Item().Text(t => { t.Span("Antivirus Active: ").Bold(); t.Span($"{_data.AntivirusEnabledCount}/{_data.TotalSystems} Systems"); });
                col.Item().Text(t => { t.Span("Windows Updates: ").Bold(); t.Span(_data.WindowsUpdateStatus); });
                col.Item().Text(t => { t.Span("BitLocker Active: ").Bold(); t.Span(_data.BitLockerStatus); });
                col.Item().Text(t => { t.Span("Unauthorized Changes: ").Bold(); t.Span(_data.UnauthorizedChangesCount.ToString()).FontColor("#EF4444"); });
                col.Item().Text(t => { t.Span("Overall Security Score: ").Bold(); t.Span($"{_data.SecurityScore:F0}%").Bold().FontColor(GetHealthScoreColor(_data.SecurityScore)); });
            });
        }

        private void ComposeSystemStatusSummary(IContainer container)
        {
            container.Border(1f).BorderColor("#E5E7EB").Padding(8f).Column(col =>
            {
                col.Item().Text(t => { t.Span("Online Systems: ").Bold(); t.Span(_data.OnlineCount.ToString()).FontColor("#10B981"); });
                col.Item().Text(t => { t.Span("Offline Systems: ").Bold(); t.Span(_data.OfflineCount.ToString()).FontColor("#6B7280"); });
                col.Item().Text(t => { t.Span("Last Collection Time: ").Bold(); t.Span(_data.LastCollectionTime); });
                col.Item().Text(t => { t.Span("Last Sync Time: ").Bold(); t.Span(_data.LastSyncTime); });

                col.Item().PaddingTop(3f).Text(t => t.Span("Agent Distribution").FontSize(8f).Bold().FontColor("#1E3A8A"));
                if (_data.AgentVersionDistribution == null || !_data.AgentVersionDistribution.Any())
                {
                    col.Item().Text(t => t.Span("No Data Available").Italic().FontSize(7f).FontColor("#6B7280"));
                }
                else
                {
                    foreach (var kvp in _data.AgentVersionDistribution)
                    {
                        col.Item().Text(t => t.Span($"• v{kvp.Key}: {kvp.Value} systems").FontSize(7.5f));
                    }
                }
            });
        }

        private void ComposeFooter(IContainer container)
        {
            container.PaddingTop(10f).Column(col =>
            {
                col.Item().LineHorizontal(0.5f).LineColor("#E5E7EB");
                col.Item().PaddingTop(3f).Row(row =>
                {
                    row.RelativeItem().Text(t =>
                    {
                        t.Span("Confidential  |  ").FontSize(7f).FontColor("#9CA3AF");
                        t.Span(_data.CompanyName).FontSize(7f).Bold().FontColor("#9CA3AF");
                        t.Span(" - DeskGuard Enterprise Report").FontSize(7f).FontColor("#9CA3AF");
                    });

                    row.ConstantItem(80f).AlignRight().Text(x =>
                    {
                        x.Span("Page ").FontSize(7f).FontColor("#9CA3AF");
                        x.CurrentPageNumber().FontSize(7f).FontColor("#9CA3AF");
                        x.Span(" of ").FontSize(7f).FontColor("#9CA3AF");
                        x.TotalPages().FontSize(7f).FontColor("#9CA3AF");
                    });
                });
            });
        }
    }
}
