using System;
using System.Linq;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using DeskGuardBackend.Reports.Models;

namespace DeskGuardBackend.Reports.PDF
{
    public class AssetInventoryReportDocument : IDocument
    {
        private readonly AssetInventoryReportData _data;

        public AssetInventoryReportDocument(AssetInventoryReportData data)
        {
            _data = data;
        }

        public DocumentMetadata GetMetadata()
        {
            return new DocumentMetadata
            {
                Title = "Asset Inventory Report",
                Author = "DeskGuard Enterprise",
                Subject = $"Asset Inventory for {_data.CompanyName}"
            };
        }

        public DocumentSettings GetSettings() => DocumentSettings.Default;

        public void Compose(IDocumentContainer container)
        {
            container
                .Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(30f, Unit.Point);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontFamily("Segoe UI").FontSize(9f).FontColor("#1F2937"));

                    page.Header().Element(ComposeHeader);
                    page.Content().Element(ComposeContent);
                    page.Footer().Element(ComposeFooter);
                });
        }

        private void ComposeHeader(IContainer container)
        {
            container.PaddingBottom(15f).Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(t => t.Span("DeskGuard").FontSize(18f).Bold().FontColor("#1E3A8A"));
                    col.Item().Text(t => t.Span("Asset Inventory Report").FontSize(14f).Bold().FontColor("#3B82F6"));
                    col.Item().Text(t => t.Span($"Customer: {_data.CompanyName}").FontSize(10f).SemiBold());
                });

                row.ConstantItem(180f).AlignRight().Column(col =>
                {
                    col.Item().Text(t => t.Span($"Report ID: #{_data.ReportId}").FontSize(8f).FontColor("#6B7280"));
                    col.Item().Text(t => t.Span($"Generated At: {_data.GeneratedAt:yyyy-MM-dd HH:mm:ss}").FontSize(8f).FontColor("#6B7280"));
                    col.Item().Text(t => t.Span($"Generated By: {_data.GeneratedBy}").FontSize(8f).FontColor("#6B7280"));
                });
            });
        }

        private void ComposeContent(IContainer container)
        {
            container.Column(col =>
            {
                // Line separator
                col.Item().LineHorizontal(1f).LineColor("#E5E7EB");
                col.Item().PaddingBottom(10f);

                // Section 1: Company Info
                col.Item().Element(ComposeCompanyInformation);
                col.Item().PaddingBottom(15f);

                // Section 2: Executive Summary Cards
                col.Item().Text(t => t.Span("Executive Summary").FontSize(11f).Bold().FontColor("#1E3A8A"));
                col.Item().PaddingBottom(5f);
                col.Item().Element(ComposeExecutiveSummary);
                col.Item().PaddingBottom(15f);

                // Section 3: Hardware Summary Table
                col.Item().Text(t => t.Span("Hardware Summary Table").FontSize(11f).Bold().FontColor("#1E3A8A"));
                col.Item().PaddingBottom(5f);
                col.Item().Element(ComposeHardwareSummaryTable);
                col.Item().PaddingBottom(15f);

                // Section 4: Asset Statistics & Missing Devices
                col.Item().Row(row =>
                {
                    row.RelativeItem().Column(statCol =>
                    {
                        statCol.Item().Text(t => t.Span("Asset Statistics").FontSize(11f).Bold().FontColor("#1E3A8A"));
                        statCol.Item().PaddingBottom(5f);
                        statCol.Item().Element(ComposeAssetStatistics);
                    });
                    
                    row.ConstantItem(15f);

                    row.RelativeItem().Column(missCol =>
                    {
                        missCol.Item().Text(t => t.Span("Missing Devices & Storage Issues").FontSize(11f).Bold().FontColor("#1E3A8A"));
                        missCol.Item().PaddingBottom(5f);
                        missCol.Item().Element(ComposeMissingDevices);
                    });
                });
                col.Item().PaddingBottom(15f);

                // Section 5: Replaced Components (Change History)
                col.Item().Text(t => t.Span("Component Replacement Logs").FontSize(11f).Bold().FontColor("#1E3A8A"));
                col.Item().PaddingBottom(5f);
                col.Item().Element(ComposeReplacedComponents);
                col.Item().PaddingBottom(15f);

                // Section 6: Recommendations
                col.Item().Text(t => t.Span("Recommendations").FontSize(11f).Bold().FontColor("#1E3A8A"));
                col.Item().PaddingBottom(5f);
                col.Item().Element(ComposeRecommendations);
                col.Item().PaddingBottom(15f);

                // Section 7: Detailed System Inventory (renders detailed card for each machine)
                col.Item().Text(t => t.Span("Detailed System Inventory").FontSize(11f).Bold().FontColor("#1E3A8A"));
                col.Item().PaddingBottom(5f);
                col.Item().Element(ComposeDetailedSystemInventory);
            });
        }

        private void ComposeCompanyInformation(IContainer container)
        {
            container.Background("#F3F4F6").Padding(10f).Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(t => { t.Span("Customer Name: ").Bold(); t.Span(_data.CompanyName); });
                    col.Item().Text(t => { t.Span("Registered Mobile: ").Bold(); t.Span(_data.RegisteredMobileNumber); });
                    col.Item().Text(t => { t.Span("Email Address: ").Bold(); t.Span(_data.Email); });
                });

                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(t => { t.Span("AMC Plan: ").Bold(); t.Span(_data.AmcPlan); });
                    col.Item().Text(t => { t.Span("AMC Start Date: ").Bold(); t.Span(_data.AmcStartDateStr); });
                    col.Item().Text(t => { t.Span("AMC End Date: ").Bold(); t.Span(_data.AmcEndDateStr); });
                });

                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(t => { t.Span("Total Monitored Systems: ").Bold(); t.Span(_data.TotalSystems.ToString()); });
                    col.Item().Text(t => { t.Span("Report Period: ").Bold(); t.Span(_data.ReportPeriodStr); });
                    col.Item().Text(t => { t.Span("Report Date: ").Bold(); t.Span(_data.GeneratedAt.ToString("yyyy-MM-dd")); });
                });
            });
        }

        private void ComposeExecutiveSummary(IContainer container)
        {
            container.Column(col =>
            {
                col.Item().Row(row =>
                {
                    StyleCard(row.RelativeItem(), "Total Systems", _data.TotalSystems.ToString(), "💻", "#3B82F6");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Total CPUs", _data.TotalCpus.ToString(), "⚡", "#10B981");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "RAM Capacity", $"{_data.TotalRamGb:F1} GB", "🛡️", "#1E3A8A");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Disk Storage", $"{_data.TotalStorageGb:F1} GB", "💾", "#8B5CF6");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "SSDs Installed", _data.TotalSsds.ToString(), "⚡", "#10B981");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "HDDs Installed", _data.TotalHdds.ToString(), "💿", "#F59E0B");
                });

                col.Item().PaddingTop(6f).Row(row =>
                {
                    StyleCard(row.RelativeItem(), "Total Monitors", _data.TotalMonitors.ToString(), "🖥️", "#3B82F6");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Total Printers", _data.TotalPrinters.ToString(), "🖨️", "#EC4899");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Net Adapters", _data.TotalNetworkAdapters.ToString(), "🔌", "#6B7280");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Graphics Cards", _data.TotalGpus.ToString(), "🎮", "#8B5CF6");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "Batteries", _data.TotalBatteries.ToString(), "🔋", "#F59E0B");
                    row.ConstantItem(6f);
                    StyleCard(row.RelativeItem(), "USB Peripherals", _data.TotalUsbDevices.ToString(), "🔌", "#10B981");
                });
            });
        }

        private void StyleCard(IContainer container, string title, string value, string icon, string colorHex)
        {
            container
                .Border(1f)
                .BorderColor("#E5E7EB")
                .Background("#FAFAFA")
                .Padding(6f)
                .Column(col =>
                {
                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Text(t => t.Span(title).FontSize(7f).SemiBold().FontColor("#4B5563"));
                        row.ConstantItem(12f).AlignRight().Text(t => t.Span(icon).FontSize(8f));
                    });
                    col.Item().PaddingTop(2f).Text(t => t.Span(value).FontSize(11f).Bold().FontColor(colorHex));
                });
        }

        private void ComposeHardwareSummaryTable(IContainer container)
        {
            if (_data.Systems == null || !_data.Systems.Any())
            {
                container.Text(t => t.Span("No Data Available").Italic().FontColor("#6B7280"));
                return;
            }

            container.Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(2f); // Name
                    columns.RelativeColumn(3f); // CPU
                    columns.RelativeColumn(1.5f); // RAM
                    columns.RelativeColumn(1.8f); // Storage
                    columns.RelativeColumn(2f); // GPU
                    columns.RelativeColumn(1.2f); // Monitor
                    columns.RelativeColumn(1.2f); // Printer
                    columns.RelativeColumn(1.3f); // Health
                });

                table.Header(header =>
                {
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Machine Name"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("CPU model"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("RAM"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Storage"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Graphics (GPU)"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Monitors"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Printers"));
                    header.Cell().Element(StyleTableHeader).Text(t => t.Span("Health"));
                });

                int index = 0;
                foreach (var s in _data.Systems)
                {
                    var isEven = index % 2 == 0;
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(s.MachineName).FontSize(7.5f).SemiBold());
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(s.Cpu.Model).FontSize(7f).FontColor("#4B5563"));
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(s.Ram.TotalCapacity).FontSize(7.5f));
                    
                    var totalDiskCap = s.Disks.Any() ? $"{s.Disks.Sum(d => double.TryParse(d.Capacity.Replace(" GB", ""), out var c) ? c : 0):F0} GB" : "Not Available";
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(totalDiskCap).FontSize(7.5f));
                    
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(s.Gpu.GpuName).FontSize(7f));
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(s.Peripherals.Monitors.Count.ToString()).FontSize(7.5f));
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(s.Peripherals.Printers.Count.ToString()).FontSize(7.5f));
                    table.Cell().Element(x => StyleTableCell(x, isEven)).Text(t => t.Span(s.HealthStatus).FontSize(7.5f).SemiBold().FontColor(GetHealthStatusColor(s.HealthStatus)));
                    index++;
                }
            });
        }

        private IContainer StyleTableHeader(IContainer container)
        {
            return container
                .Background("#1E3A8A")
                .Padding(4f)
                .AlignMiddle()
                .DefaultTextStyle(x => x.FontColor(Colors.White).FontSize(7.5f).Bold());
        }

        private IContainer StyleTableCell(IContainer container, bool isEven)
        {
            return container
                .Background(isEven ? "#FFFFFF" : "#F9FAFB")
                .BorderBottom(1f)
                .BorderColor("#F3F4F6")
                .Padding(4f)
                .AlignMiddle();
        }

        private string GetHealthStatusColor(string health)
        {
            if (health.Equals("Healthy", StringComparison.OrdinalIgnoreCase) || health.Equals("Online", StringComparison.OrdinalIgnoreCase)) return "#10B981";
            if (health.Equals("Warning", StringComparison.OrdinalIgnoreCase)) return "#F59E0B";
            if (health.Equals("Offline", StringComparison.OrdinalIgnoreCase)) return "#6B7280";
            return "#EF4444";
        }

        private void ComposeAssetStatistics(IContainer container)
        {
            container.Border(1f).BorderColor("#E5E7EB").Padding(8f).Column(col =>
            {
                col.Item().Text(t => { t.Span("Laptop Count: ").Bold(); t.Span($"{_data.LaptopCount} systems"); });
                col.Item().Text(t => { t.Span("Desktop Count: ").Bold(); t.Span($"{_data.DesktopCount} systems"); });
                
                col.Item().PaddingTop(3f).Text(t => t.Span("Processor Brands").FontSize(8f).Bold().FontColor("#1E3A8A"));
                foreach (var kvp in _data.CpuBrandDistribution)
                {
                    col.Item().Text(t => t.Span($"• {kvp.Key}: {kvp.Value} CPUs").FontSize(7.5f));
                }

                col.Item().PaddingTop(3f).Text(t => t.Span("Graphics Vendors").FontSize(8f).Bold().FontColor("#1E3A8A"));
                foreach (var kvp in _data.GpuBrandDistribution)
                {
                    col.Item().Text(t => t.Span($"• {kvp.Key}: {kvp.Value} GPU(s)").FontSize(7.5f));
                }
            });
        }

        private void ComposeMissingDevices(IContainer container)
        {
            container.Border(1f).BorderColor("#E5E7EB").Padding(8f).Column(col =>
            {
                var auditIssues = _data.MissingDevices;
                if (auditIssues == null || !auditIssues.Any())
                {
                    col.Item().Text(t => t.Span("All systems compliant (No missing peripherals or storage warnings detected)").Italic().FontColor("#4B5563"));
                    return;
                }

                foreach (var issue in auditIssues.Take(8))
                {
                    col.Item().Text(t =>
                    {
                        t.Span($"⚡ {issue.MachineName}: ").Bold().FontColor("#EF4444");
                        t.Span(issue.Detail).FontSize(7.5f);
                    });
                }
                if (auditIssues.Count > 8)
                {
                    col.Item().Text(t => t.Span($"... and {auditIssues.Count - 8} more warnings").Italic().FontSize(7.5f).FontColor("#6B7280"));
                }
            });
        }

        private void ComposeReplacedComponents(IContainer container)
        {
            if (_data.ReplacedComponents == null || !_data.ReplacedComponents.Any())
            {
                container.Border(1f).BorderColor("#E5E7EB").Padding(8f).Text(t => t.Span("No components replaced during this period").Italic().FontColor("#6B7280"));
                return;
            }

            container.Border(1f).BorderColor("#E5E7EB").Padding(8f).Column(col =>
            {
                foreach (var replacement in _data.ReplacedComponents.Take(5))
                {
                    col.Item().Text(t =>
                    {
                        t.Span($"⚙️ {replacement.MachineName}: ").Bold().FontColor("#3B82F6");
                        t.Span($"{replacement.Detail} ({replacement.DetectedAt})").FontSize(7.5f);
                    });
                }
                if (_data.ReplacedComponents.Count > 5)
                {
                    col.Item().Text(t => t.Span($"... and {_data.ReplacedComponents.Count - 5} more replacements logged").Italic().FontSize(7.5f).FontColor("#6B7280"));
                }
            });
        }

        private void ComposeRecommendations(IContainer container)
        {
            container
                .Border(1f)
                .BorderColor("#EF4444")
                .Background("#FEF2F2")
                .Padding(10f)
                .Column(col =>
                {
                    foreach (var recommendation in _data.Recommendations)
                    {
                        col.Item().Row(row =>
                        {
                            row.ConstantItem(12f).Text(t => t.Span("⚡").FontColor("#EF4444").Bold());
                            row.RelativeItem().Text(t => t.Span(recommendation).FontSize(8.5f).SemiBold());
                        });
                    }
                });
        }

        private void ComposeDetailedSystemInventory(IContainer container)
        {
            container.Column(col =>
            {
                int itemIdx = 0;
                foreach (var sys in _data.Systems)
                {
                    if (itemIdx > 0)
                    {
                        col.Item().PaddingTop(15f).LineHorizontal(0.5f).LineColor("#E5E7EB");
                    }

                    col.Item().PaddingTop(10f).Column(sysCol =>
                    {
                        // Header bar for the machine
                        sysCol.Item().Background("#1E3A8A").Padding(6f).Row(row =>
                        {
                            row.RelativeItem().Text(t => t.Span($"System: {sys.MachineName} (ID: {sys.MachineId})").FontSize(10f).Bold().FontColor(Colors.White));
                            row.ConstantItem(100f).AlignRight().Text(t => t.Span(sys.HealthStatus).FontSize(10f).Bold().FontColor(Colors.White));
                        });

                        // Main System Specs layout
                        sysCol.Item().Padding(8f).Border(1f).BorderColor("#E5E7EB").Row(row =>
                        {
                            // Left Column (Specs)
                            row.RelativeItem().Column(leftCol =>
                            {
                                leftCol.Item().Text(t => { t.Span("Operating System: ").Bold(); t.Span(sys.OperatingSystem); });
                                leftCol.Item().Text(t => { t.Span("Current Logged User: ").Bold(); t.Span(sys.CurrentUser); });
                                leftCol.Item().Text(t => { t.Span("Last Telemetry Collected: ").Bold(); t.Span(sys.LastInventoryUpdate); });
                                leftCol.Item().Text(t => { t.Span("Last Network Heartbeat: ").Bold(); t.Span(sys.LastHeartbeat); });

                                // CPU Details
                                leftCol.Item().PaddingTop(4f).Text(t => t.Span("CPU Details").Bold().FontColor("#1E3A8A").Underline());
                                leftCol.Item().Text(t => { t.Span("Model: ").Bold(); t.Span(sys.Cpu.Model); });
                                leftCol.Item().Text(t => { t.Span("Clock Speed: ").Bold(); t.Span(sys.Cpu.ClockSpeed); });
                                leftCol.Item().Text(t => { t.Span("Cores/Threads: ").Bold(); t.Span($"{sys.Cpu.CoreCount} Cores, {sys.Cpu.LogicalProcessors} Threads ({sys.Cpu.Generation})"); });

                                // RAM Details
                                leftCol.Item().PaddingTop(4f).Text(t => t.Span("RAM details").Bold().FontColor("#1E3A8A").Underline());
                                leftCol.Item().Text(t => { t.Span("Capacity: ").Bold(); t.Span(sys.Ram.TotalCapacity); });
                                leftCol.Item().Text(t => { t.Span("Speed/Type: ").Bold(); t.Span($"{sys.Ram.Speed} {sys.Ram.Type}"); });
                                leftCol.Item().Text(t => { t.Span("Slots: ").Bold(); t.Span(sys.Ram.SlotCount); });
                                if (sys.Ram.IndividualModules.Any())
                                {
                                    leftCol.Item().Text(t => { t.Span("Individual Modules: ").Bold(); t.Span(string.Join(", ", sys.Ram.IndividualModules)); });
                                }

                                // GPU Details
                                leftCol.Item().PaddingTop(4f).Text(t => t.Span("Graphics (GPU) Details").Bold().FontColor("#1E3A8A").Underline());
                                leftCol.Item().Text(t => { t.Span("Model: ").Bold(); t.Span(sys.Gpu.GpuName); });
                                leftCol.Item().Text(t => { t.Span("Memory: ").Bold(); t.Span(sys.Gpu.Memory); });
                                leftCol.Item().Text(t => { t.Span("Driver Version: ").Bold(); t.Span(sys.Gpu.DriverVersion); });
                            });

                            row.ConstantItem(12f);

                            // Right Column (Motherboard, Battery, Network, Storage, Peripherals)
                            row.RelativeItem().Column(rightCol =>
                            {
                                // Motherboard Details
                                rightCol.Item().Text(t => t.Span("Motherboard Details").Bold().FontColor("#1E3A8A").Underline());
                                rightCol.Item().Text(t => { t.Span("Model/Brand: ").Bold(); t.Span($"{sys.Motherboard.Manufacturer} {sys.Motherboard.Model}"); });
                                rightCol.Item().Text(t => { t.Span("Serial: ").Bold(); t.Span(sys.Motherboard.SerialNumber); });
                                rightCol.Item().Text(t => { t.Span("BIOS Version: ").Bold(); t.Span(sys.Motherboard.BiosVersion); });

                                // Laptop Battery Details
                                if (sys.Battery.IsPresent)
                                {
                                    rightCol.Item().PaddingTop(4f).Text(t => t.Span("Battery Details").Bold().FontColor("#1E3A8A").Underline());
                                    rightCol.Item().Text(t => { t.Span("Status/Health: ").Bold(); t.Span($"{sys.Battery.Status} (Health: {sys.Battery.Health})"); });
                                    rightCol.Item().Text(t => { t.Span("Capacity: ").Bold(); t.Span(sys.Battery.Capacity); });
                                }

                                // Network Adapters
                                rightCol.Item().PaddingTop(4f).Text(t => t.Span("Network Interfaces").Bold().FontColor("#1E3A8A").Underline());
                                foreach (var net in sys.NetworkAdapters.Take(3))
                                {
                                    rightCol.Item().Text(t => t.Span($"• [{net.AdapterType}] {net.AdapterName} (MAC: {net.MacAddress})").FontSize(7.5f));
                                }

                                // Storage Disks
                                rightCol.Item().PaddingTop(4f).Text(t => t.Span("Storage Drives").Bold().FontColor("#1E3A8A").Underline());
                                foreach (var dk in sys.Disks)
                                {
                                    rightCol.Item().Text(t => t.Span($"• Drive {dk.DriveLetter}: [{dk.DriveType}] {dk.Capacity} (SMART: {dk.SmartStatus})").FontSize(7.5f));
                                }

                                // Peripherals
                                rightCol.Item().PaddingTop(4f).Text(t => t.Span("Monitors & Peripherals").Bold().FontColor("#1E3A8A").Underline());
                                var monitorNames = sys.Peripherals.Monitors.Any() ? string.Join(", ", sys.Peripherals.Monitors) : "Not Available";
                                rightCol.Item().Text(t => { t.Span("Monitors: ").Bold(); t.Span(monitorNames); });
                                
                                var printerNames = sys.Peripherals.Printers.Any() ? string.Join(", ", sys.Peripherals.Printers) : "Not Available";
                                rightCol.Item().Text(t => { t.Span("Printers: ").Bold(); t.Span(printerNames); });

                                var webcams = sys.Peripherals.Webcams.Any() ? string.Join(", ", sys.Peripherals.Webcams) : "Not Available";
                                rightCol.Item().Text(t => { t.Span("Webcams: ").Bold(); t.Span(webcams); });

                                var usbCount = sys.Peripherals.UsbDevices.Count;
                                rightCol.Item().Text(t => { t.Span("USB Connected Devices: ").Bold(); t.Span($"{usbCount} active devices connected"); });
                            });
                        });
                    });

                    itemIdx++;
                }
            });
        }

        private void ComposeFooter(IContainer container)
        {
            container.PaddingTop(10f).Column(col =>
            {
                col.Item().LineHorizontal(0.5f).LineColor("#E5E7EB");
                col.Item().PaddingTop(3f).Row(row =>
                {
                    row.RelativeItem().Text(t =>
                    {
                        t.Span("Confidential  |  ").FontSize(7f).FontColor("#9CA3AF");
                        t.Span(_data.CompanyName).FontSize(7f).Bold().FontColor("#9CA3AF");
                        t.Span(" - DeskGuard IT Asset Inventory Report").FontSize(7f).FontColor("#9CA3AF");
                    });

                    row.ConstantItem(80f).AlignRight().Text(x =>
                    {
                        x.Span("Page ").FontSize(7f).FontColor("#9CA3AF");
                        x.CurrentPageNumber().FontSize(7f).FontColor("#9CA3AF");
                        x.Span(" of ").FontSize(7f).FontColor("#9CA3AF");
                        x.TotalPages().FontSize(7f).FontColor("#9CA3AF");
                    });
                });
            });
        }
    }
}
