using System;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using DeskGuardBackend.Reports.Models;

namespace DeskGuardBackend.Reports.PDF
{
    /// <summary>
    /// Enterprise base document template for all single-machine reports.
    /// Provides consistent header, footer, color palette, and styling.
    /// Subclasses override ComposeReportContent to render their unique content.
    /// </summary>
    public abstract class MachineReportBaseDocument : IDocument
    {
        // =====================================================================
        // ENTERPRISE COLOR PALETTE
        // =====================================================================
        protected const string ColorPrimary = "#1E3A8A";      // Dark Blue
        protected const string ColorAccent = "#3B82F6";        // Light Blue
        protected const string ColorBackground = "#F8FAFC";    // Very Light Gray
        protected const string ColorBorder = "#E2E8F0";        // Border Gray
        protected const string ColorTextPrimary = "#1E293B";   // Near Black
        protected const string ColorTextSecondary = "#64748B";  // Medium Gray
        protected const string ColorTableHeader = "#1E3A8A";    // Dark Blue
        protected const string ColorTableRowEven = "#FFFFFF";   // White
        protected const string ColorTableRowOdd = "#F8FAFC";    // Very Light Gray
        protected const string ColorSuccess = "#16A34A";        // Green
        protected const string ColorWarning = "#D97706";        // Amber
        protected const string ColorDanger = "#DC2626";         // Red
        protected const string ColorInfo = "#2563EB";           // Blue

        protected readonly MachineReportMetadata _metadata;

        protected MachineReportBaseDocument(MachineReportMetadata metadata)
        {
            _metadata = metadata;
        }

        public DocumentMetadata GetMetadata() => new DocumentMetadata
        {
            Title = _metadata.ReportTitle,
            Author = "DeskGuard Enterprise",
            Subject = $"{_metadata.ReportTitle} - {_metadata.MachineName}"
        };

        public DocumentSettings GetSettings() => DocumentSettings.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30f, Unit.Point);
                page.PageColor(Colors.White);
                page.DefaultTextStyle(x => x
                    .FontFamily("Segoe UI")
                    .FontSize(9f)
                    .FontColor(ColorTextPrimary));

                page.Header().Element(ComposeHeader);
                page.Content().Element(ComposeBody);
                page.Footer().Element(ComposeFooter);
            });
        }

        // =====================================================================
        // HEADER — Consistent across all reports
        // =====================================================================
        private void ComposeHeader(IContainer container)
        {
            var displayUid = _metadata.MachineUid?.Length > 28 ? _metadata.MachineUid.Substring(0, 28) + "..." : _metadata.MachineUid;

            container.Column(col =>
            {
                col.Item().PaddingBottom(4f).Row(row =>
                {
                    row.RelativeItem().Column(left =>
                    {
                        left.Item().Text(t => t.Span("DeskGuard")
                            .FontSize(18f).Bold().FontColor(ColorPrimary));
                        left.Item().Text(t => t.Span(_metadata.ReportTitle)
                            .FontSize(12f).Bold().FontColor(ColorAccent));
                    });

                    row.ConstantItem(200f).AlignRight().Column(right =>
                    {
                        right.Item().Text(t => t.Span($"Report ID: {_metadata.ReportId}")
                            .FontSize(7.5f).FontColor(ColorTextSecondary));
                        right.Item().Text(t => t.Span($"Generated: {_metadata.GeneratedAt:yyyy-MM-dd HH:mm:ss} UTC")
                            .FontSize(7.5f).FontColor(ColorTextSecondary));
                        right.Item().Text(t => t.Span($"Generated By: {_metadata.GeneratedBy}")
                            .FontSize(7.5f).FontColor(ColorTextSecondary));
                    });
                });

                // Machine info bar
                col.Item().Background(ColorBackground).Border(1f).BorderColor(ColorBorder)
                    .Padding(5f).Row(row =>
                {
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text(t => { t.Span("Machine: ").FontSize(8f).SemiBold(); t.Span(_metadata.MachineName).FontSize(8f); });
                        c.Item().Text(t => { t.Span("Machine ID: ").FontSize(8f).SemiBold(); t.Span(displayUid).FontSize(8f); });
                    });
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text(t => { t.Span("OS: ").FontSize(8f).SemiBold(); t.Span(_metadata.OperatingSystem).FontSize(8f); });
                        c.Item().Text(t => { t.Span("Company: ").FontSize(8f).SemiBold(); t.Span(_metadata.CompanyName).FontSize(8f); });
                    });
                    row.RelativeItem().AlignRight().Column(c =>
                    {
                        c.Item().Text(t => { t.Span("Period: ").FontSize(8f).SemiBold(); t.Span(_metadata.ReportPeriod).FontSize(8f); });
                    });
                });

                col.Item().PaddingTop(4f).LineHorizontal(1f).LineColor(ColorBorder);
            });
        }

        // =====================================================================
        // BODY — Delegates to subclass
        // =====================================================================
        private void ComposeBody(IContainer container)
        {
            container.PaddingTop(8f).Element(ComposeReportContent);
        }

        /// <summary>
        /// Subclasses implement this to render report-specific content.
        /// </summary>
        protected abstract void ComposeReportContent(IContainer container);

        // =====================================================================
        // FOOTER — Consistent across all reports
        // =====================================================================
        private void ComposeFooter(IContainer container)
        {
            container.Column(col =>
            {
                col.Item().LineHorizontal(0.5f).LineColor(ColorBorder);
                col.Item().PaddingTop(4f).Row(row =>
                {
                    row.RelativeItem().Text(t =>
                    {
                        t.Span("CONFIDENTIAL").FontSize(6.5f).Bold().FontColor(ColorTextSecondary);
                        t.Span("  |  DeskGuard Enterprise  |  ").FontSize(6.5f).FontColor(ColorTextSecondary);
                        t.Span(_metadata.GeneratedAt.ToString("yyyy-MM-dd")).FontSize(6.5f).FontColor(ColorTextSecondary);
                    });
                    row.ConstantItem(80f).AlignRight().Text(t =>
                    {
                        t.Span("Page ").FontSize(6.5f).FontColor(ColorTextSecondary);
                        t.CurrentPageNumber().FontSize(6.5f).FontColor(ColorTextSecondary);
                        t.Span(" of ").FontSize(6.5f).FontColor(ColorTextSecondary);
                        t.TotalPages().FontSize(6.5f).FontColor(ColorTextSecondary);
                    });
                });
            });
        }

        // =====================================================================
        // SHARED HELPER METHODS — Available to all subclasses
        // =====================================================================

        /// <summary>Section title with accent bar.</summary>
        protected void SectionTitle(IContainer container, string title)
        {
            container.PaddingBottom(4f).Row(row =>
            {
                row.ConstantItem(3f).Background(ColorAccent).ExtendVertical();
                row.RelativeItem().PaddingLeft(6f).Text(t =>
                    t.Span(title).FontSize(10.5f).Bold().FontColor(ColorPrimary));
            });
        }

        /// <summary>Key-value info row.</summary>
        protected void InfoRow(IContainer container, string label, string value)
        {
            container.PaddingVertical(1f).Row(row =>
            {
                row.ConstantItem(130f).Text(t => t.Span(label).FontSize(8f).SemiBold().FontColor(ColorTextSecondary));
                row.RelativeItem().Text(t => t.Span(value ?? "No Data Available").FontSize(8f).FontColor(ColorTextPrimary));
            });
        }

        /// <summary>Styled table header cell.</summary>
        protected IContainer TableHeaderCell(IContainer container)
        {
            return container
                .Background(ColorTableHeader)
                .Padding(5f)
                .AlignMiddle()
                .DefaultTextStyle(x => x.FontColor(Colors.White).FontSize(7.5f).Bold());
        }

        /// <summary>Styled table data cell with alternating row colors.</summary>
        protected IContainer TableDataCell(IContainer container, bool isEven)
        {
            return container
                .Background(isEven ? ColorTableRowEven : ColorTableRowOdd)
                .BorderBottom(1f)
                .BorderColor(ColorBorder)
                .Padding(4f)
                .AlignMiddle();
        }

        /// <summary>Summary metric card.</summary>
        protected void MetricCard(IContainer container, string label, string value, string color)
        {
            container.Border(1f).BorderColor(ColorBorder).Background(Colors.White)
                .Padding(10f).Column(col =>
                {
                    col.Item().Text(t => t.Span(label).FontSize(7.5f).SemiBold().FontColor(ColorTextSecondary));
                    col.Item().PaddingTop(4f).Text(t => t.Span(value).FontSize(14f).Bold().FontColor(color));
                });
        }

        /// <summary>Get color for severity badges.</summary>
        protected string GetSeverityColor(string severity)
        {
            return severity?.ToLower() switch
            {
                "critical" => ColorDanger,
                "warning" => ColorWarning,
                "info" or "information" => ColorInfo,
                _ => ColorTextSecondary
            };
        }

        /// <summary>Get color for status badges.</summary>
        protected string GetStatusColor(string status)
        {
            return status?.ToLower() switch
            {
                "open" => ColorWarning,
                "acknowledged" => ColorInfo,
                "resolved" => ColorSuccess,
                "online" => ColorSuccess,
                "offline" => ColorTextSecondary,
                "running" => ColorSuccess,
                "stopped" => ColorDanger,
                _ => ColorTextSecondary
            };
        }
    }
}
