/// <summary>
/// Represents a monitored machine (desktop, laptop, server) in the DeskGuard system.
/// Each machine is assigned to a company and optionally linked to a user (employee).
/// This is the central entity — most telemetry data links back to a Machine.
/// Maps to the 'machines' table in PostgreSQL.
/// </summary>
namespace DeskGuardBackend.Entities
{
    public class Machine
    {
        /// <summary>Primary key. Auto-incremented.</summary>
        public long Id { get; set; }

        /// <summary>FK to the company this machine belongs to.</summary>
        public long? CompanyId { get; set; }

        /// <summary>FK to the AMC customer this machine belongs to.</summary>
        public long? CustomerId { get; set; }

        /// <summary>FK to the user this machine is assigned to (nullable).</summary>
        public long? UserId { get; set; }

        /// <summary>Unique machine identifier generated by the agent.</summary>
        public string MachineUid { get; set; } = string.Empty;

        /// <summary>Computer hostname.</summary>
        public string? Hostname { get; set; }

        /// <summary>Device display name.</summary>
        public string? DeviceName { get; set; }

        /// <summary>Operating system name (e.g., "Windows 11 Pro").</summary>
        public string? OperatingSystem { get; set; }

        /// <summary>OS version string.</summary>
        public string? OsVersion { get; set; }

        /// <summary>Hardware manufacturer.</summary>
        public string? Manufacturer { get; set; }

        /// <summary>Hardware model name.</summary>
        public string? Model { get; set; }

        /// <summary>Device serial number.</summary>
        public string? SerialNumber { get; set; }

        /// <summary>BIOS version string.</summary>
        public string? BiosVersion { get; set; }

        /// <summary>Processor name/model.</summary>
        public string? Processor { get; set; }

        /// <summary>Total installed RAM in GB.</summary>
        public int? RamGb { get; set; }

        /// <summary>Whether the machine is currently online (heartbeat within threshold).</summary>
        public bool IsOnline { get; set; }

        /// <summary>Timestamp of last heartbeat received from the agent.</summary>
        public DateTime? LastHeartbeatAt { get; set; }

        /// <summary>FK to a custom alert profile override for this machine.</summary>
        public long? CustomAlertProfileId { get; set; }

        /// <summary>Token used during initial machine activation.</summary>
        public string? ActivationToken { get; set; }

        /// <summary>Timestamp when the machine was activated.</summary>
        public DateTime? ActivatedAt { get; set; }

        /// <summary>Whether the machine is active in the system.</summary>
        public bool IsActive { get; set; } = true;

        /// <summary>Machine API token (plain text, transient — used only during registration response).</summary>
        public string? ApiToken { get; set; }

        /// <summary>Employee mobile number associated with this machine.</summary>
        public string? EmployeeMobileNumber { get; set; }

        /// <summary>Record creation timestamp (UTC).</summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Record last update timestamp (UTC).</summary>
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        // Navigation properties
        /// <summary>Company this machine belongs to.</summary>
        public Company? Company { get; set; }

        /// <summary>AMC Customer this machine belongs to.</summary>
        public Customer? Customer { get; set; }

        /// <summary>User this machine is assigned to.</summary>
        public User? AssignedUser { get; set; }

        /// <summary>Current real-time status snapshot (1:1).</summary>
        public MachineCurrentStatus? CurrentStatus { get; set; }

        /// <summary>Machine authentication tokens.</summary>
        public ICollection<MachineToken> MachineTokens { get; set; } = new List<MachineToken>();

        /// <summary>Historical health metrics log.</summary>
        public ICollection<HealthLog> HealthLogs { get; set; } = new List<HealthLog>();

        /// <summary>Alerts generated for this machine.</summary>
        public ICollection<Alert> Alerts { get; set; } = new List<Alert>();

        /// <summary>Hardware inventory snapshots.</summary>
        public ICollection<HardwareInventory> HardwareInventories { get; set; } = new List<HardwareInventory>();

        /// <summary>Installed software inventory.</summary>
        public ICollection<SoftwareInventory> SoftwareInventories { get; set; } = new List<SoftwareInventory>();

        /// <summary>Connected peripheral devices.</summary>
        public ICollection<MachineConnectedDevice> ConnectedDevices { get; set; } = new List<MachineConnectedDevice>();

        /// <summary>Network adapters on this machine.</summary>
        public ICollection<MachineNetworkAdapter> NetworkAdapters { get; set; } = new List<MachineNetworkAdapter>();

        /// <summary>Disk drives on this machine.</summary>
        public ICollection<MachineDisk> Disks { get; set; } = new List<MachineDisk>();

        /// <summary>Login activity events.</summary>
        public ICollection<LoginActivity> LoginActivities { get; set; } = new List<LoginActivity>();

        /// <summary>USB activity events.</summary>
        public ICollection<UsbActivity> UsbActivities { get; set; } = new List<UsbActivity>();

        /// <summary>Windows service statuses.</summary>
        public ICollection<WindowsService> WindowsServices { get; set; } = new List<WindowsService>();

        /// <summary>Windows update statuses.</summary>
        public ICollection<WindowsUpdate> WindowsUpdates { get; set; } = new List<WindowsUpdate>();

        /// <summary>Running process snapshots.</summary>
        public ICollection<ProcessLog> ProcessLogs { get; set; } = new List<ProcessLog>();

        /// <summary>Windows event log entries.</summary>
        public ICollection<EventLog> EventLogs { get; set; } = new List<EventLog>();

        /// <summary>Startup programs.</summary>
        public ICollection<StartupProgram> StartupPrograms { get; set; } = new List<StartupProgram>();

        /// <summary>Device events (connect/disconnect).</summary>
        public ICollection<DeviceEvent> DeviceEvents { get; set; } = new List<DeviceEvent>();

        /// <summary>Change history records.</summary>
        public ICollection<ChangeHistory> ChangeHistories { get; set; } = new List<ChangeHistory>();

        /// <summary>Custom alert profile override for this machine.</summary>
        public AlertProfile? CustomAlertProfile { get; set; }
    }
}
