/// <summary>
/// Represents a user account in the DeskGuard system.
/// Users are scoped to a company and support role-based access control.
/// Supports soft deletes and password change enforcement.
/// Maps to the 'users' table in PostgreSQL.
/// </summary>
namespace DeskGuardBackend.Entities
{
    public class User
    {
        /// <summary>Primary key. Auto-incremented.</summary>
        public long Id { get; set; }

        /// <summary>FK to the company this user belongs to (nullable for OTP-created users).</summary>
        public long? CompanyId { get; set; }

        /// <summary>Mobile number used for OTP authentication.</summary>
        public string? MobileNumber { get; set; }

        /// <summary>User display name.</summary>
        public string? Name { get; set; }

        /// <summary>User email (unique, used for login).</summary>
        public string? Email { get; set; }

        /// <summary>BCrypt-hashed password.</summary>
        [System.Text.Json.Serialization.JsonIgnore]
        public string? Password { get; set; }

        /// <summary>Whether mobile number has been verified via OTP.</summary>
        public bool IsVerified { get; set; }

        /// <summary>User phone number.</summary>
        public string? Phone { get; set; }

        /// <summary>Avatar image URL.</summary>
        public string? Avatar { get; set; }

        /// <summary>Whether the user account is active.</summary>
        public bool IsActive { get; set; } = true;

        /// <summary>Whether user must change password on next login.</summary>
        public bool MustChangePassword { get; set; }

        /// <summary>Timestamp of last successful login.</summary>
        public DateTime? LastLoginAt { get; set; }

        /// <summary>Record creation timestamp (UTC).</summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Record last update timestamp (UTC).</summary>
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Soft delete timestamp (null = not deleted).</summary>
        public DateTime? DeletedAt { get; set; }

        /// <summary>Activation token for agent registration flow.</summary>
        public string? ActivationToken { get; set; }

        /// <summary>Employee ID in EMP-XXXX format (unique, for admin accounts).</summary>
        public string? EmployeeId { get; set; }

        /// <summary>FK to the User who created this account (for admin accounts).</summary>
        public long? CreatedByUserId { get; set; }

        /// <summary>Creator of this account (navigation).</summary>
        public User? CreatedBy { get; set; }

        // Navigation properties
        /// <summary>Company this user belongs to.</summary>
        public Company? Company { get; set; }

        /// <summary>Machines assigned to this user.</summary>
        public ICollection<Machine> Machines { get; set; } = new List<Machine>();

        /// <summary>Reports generated by this user.</summary>
        public ICollection<Report> Reports { get; set; } = new List<Report>();

        /// <summary>Audit log entries for this user.</summary>
        public ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

        /// <summary>User's assigned roles (many-to-many).</summary>
        public ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
    }
}
