using System;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DeskGuardBackend.DTOs.Common;
using DeskGuardBackend.Reports.Interfaces;
using DeskGuardBackend.Reports.Models;

namespace DeskGuardBackend.Reports.Controllers
{
    [Authorize]
    [ApiController]
    [Route("api/v1/reports")]
    public class ReportApiController : ControllerBase
    {
        private readonly IReportGenerationService _reportService;
        private readonly IMachineReportService _machineReportService;
        private readonly ILogger<ReportApiController> _logger;

        public ReportApiController(
            IReportGenerationService reportService,
            IMachineReportService machineReportService,
            ILogger<ReportApiController> logger)
        {
            _reportService = reportService;
            _machineReportService = machineReportService;
            _logger = logger;
        }

        [HttpGet("machine")]
        public async Task<IActionResult> GetMachineReport(
            [FromQuery] long machineId,
            [FromQuery] string reportType = "health",
            [FromQuery] DateTime? dateFrom = null,
            [FromQuery] DateTime? dateTo = null)
        {
            try
            {
                var userCompanyId = GetCurrentUserCompanyId();
                var currentUserName = GetCurrentUserName();

                var pdfBytes = await _machineReportService.GenerateReportAsync(
                    machineId, reportType, dateFrom, dateTo, currentUserName, userCompanyId);

                var cleanType = (reportType ?? "health").Replace("_", "-").ToLower();
                var fileName = $"Machine_{machineId}_{cleanType}_{DateTime.UtcNow:yyyyMMdd}.pdf";

                return File(pdfBytes, "application/pdf", fileName);
            }
            catch (KeyNotFoundException ex)
            {
                return NotFound(ApiResponse.Fail(ex.Message));
            }
            catch (ArgumentException ex)
            {
                return BadRequest(ApiResponse.Fail(ex.Message));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to generate machine report for machine {MachineId}: {Message}", machineId, ex.Message);
                return StatusCode(500, ApiResponse.Fail($"Failed to generate machine report: {ex.Message}"));
            }
        }

        [HttpGet("amc-health-summary")]
        public async Task<IActionResult> GetAmcHealthSummaryReport([FromQuery] AmcHealthSummaryQueryParameters queryParams)
        {
            try
            {
                // 1. Role validation: Must be Admin or Super Admin
                var userRole = GetCurrentUserRole();
                if (userRole != "Admin" && userRole != "Super Admin")
                {
                    return Forbid();
                }

                // 2. Ownership / Tenant Boundary validation
                var userCompanyId = GetCurrentUserCompanyId();
                var targetCompanyId = queryParams.CompanyId ?? queryParams.CustomerId ?? userCompanyId;

                // Non-Super Admins are locked to their own company
                if (userRole != "Super Admin" && targetCompanyId != userCompanyId)
                {
                    return Forbid();
                }

                // Align the queryParams target company
                queryParams.CompanyId = targetCompanyId;

                // Get current username for "Generated By" metadata
                var currentUserName = GetCurrentUserName();

                // 3. Fetch data
                var reportData = await _reportService.GetAmcHealthSummaryDataAsync(queryParams);
                reportData.GeneratedBy = currentUserName;

                // 4. Generate PDF bytes
                var pdfBytes = _reportService.GenerateAmcHealthSummaryPdf(reportData);

                // Format filename: AMC_Health_Summary_<CustomerName>_<YYYYMMDD>.pdf
                var sanitizedCompanyName = SanitizeFileName(reportData.CompanyName);
                var fileName = $"AMC_Health_Summary_{sanitizedCompanyName}_{DateTime.UtcNow:yyyyMMdd}.pdf";

                return File(pdfBytes, "application/pdf", fileName);
            }
            catch (KeyNotFoundException ex)
            {
                return NotFound(ApiResponse.Fail(ex.Message));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to generate AMC Health Summary report API response");
                return StatusCode(500, ApiResponse.Fail("Failed to generate report."));
            }
        }

        [HttpGet("asset-inventory")]
        public async Task<IActionResult> GetAssetInventoryReport([FromQuery] AssetInventoryQueryParameters queryParams)
        {
            try
            {
                // 1. Role validation: Must be Admin or Super Admin
                var userRole = GetCurrentUserRole();
                if (userRole != "Admin" && userRole != "Super Admin")
                {
                    return Forbid();
                }

                // 2. Ownership / Tenant Boundary validation
                var userCompanyId = GetCurrentUserCompanyId();
                var targetCompanyId = queryParams.CompanyId ?? queryParams.CustomerId ?? userCompanyId;

                // Non-Super Admins are locked to their own company
                if (userRole != "Super Admin" && targetCompanyId != userCompanyId)
                {
                    return Forbid();
                }

                // Align the queryParams target company
                queryParams.CompanyId = targetCompanyId;

                // Get current username for "Generated By" metadata
                var currentUserName = GetCurrentUserName();

                // 3. Fetch data
                var reportData = await _reportService.GetAssetInventoryDataAsync(queryParams);
                reportData.GeneratedBy = currentUserName;

                // 4. Generate PDF bytes
                var pdfBytes = _reportService.GenerateAssetInventoryPdf(reportData);

                // Format filename: Asset_Inventory_<CustomerName>_<YYYYMMDD>.pdf
                var sanitizedCompanyName = SanitizeFileName(reportData.CompanyName);
                var fileName = $"Asset_Inventory_{sanitizedCompanyName}_{DateTime.UtcNow:yyyyMMdd}.pdf";

                return File(pdfBytes, "application/pdf", fileName);
            }
            catch (KeyNotFoundException ex)
            {
                return NotFound(ApiResponse.Fail(ex.Message));
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to generate Asset Inventory report API response");
                return StatusCode(500, ApiResponse.Fail("Failed to generate report."));
            }
        }

        private string GetCurrentUserRole()
        {
            return User.FindFirst(ClaimTypes.Role)?.Value ?? "User";
        }

        private long GetCurrentUserCompanyId()
        {
            var compIdStr = User.FindFirst("CompanyId")?.Value;
            return long.TryParse(compIdStr, out var companyId) ? companyId : 1;
        }

        private string GetCurrentUserName()
        {
            return User.FindFirst("Name")?.Value ?? User.FindFirst(ClaimTypes.Name)?.Value ?? "Administrator";
        }

        private string SanitizeFileName(string name)
        {
            var invalidChars = System.IO.Path.GetInvalidFileNameChars();
            var clean = new string(name.Where(c => !invalidChars.Contains(c)).ToArray());
            return clean.Replace(" ", "_");
        }
    }
}
